language: go
go:
- 1.12.x

git:
  depth: false

env:
  - GO111MODULE=off
  
install:
  - go get github.com/mattn/goveralls

before_script:
- EXCLUDE_VENDOR=$(go list ./... | grep -v "/vendor/")
- $(exit $(go fmt $EXCLUDE_VENDOR | wc -l))
- go vet $EXCLUDE_VENDOR

script:
- go test -race -coverpkg=./... -coverprofile=./coverage.out ./...

after_success:
- git reset --hard
